Watching for file changes with StatReloader
[15/Feb/2020 01:06:25] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:06:34] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:06:44] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:06:54] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:07:04] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:07:14] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:07:25] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:07:34] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:07:44] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:07:54] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:08:04] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:08:14] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:08:25] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:08:34] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:08:44] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:08:54] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:09:04] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:09:14] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:09:25] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:09:35] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:09:44] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:09:54] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:10:04] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:10:14] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:10:25] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:10:34] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:10:44] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:10:54] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:11:04] "GET /api/newsinfoList/ HTTP/1.1" 200 16
Watching for file changes with StatReloader
[15/Feb/2020 01:11:14] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:11:25] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:11:34] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:11:44] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:11:54] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:12:04] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:12:14] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:12:25] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:12:34] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:12:44] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:12:45] "GET /api/dustinfo/ HTTP/1.1" 200 212
[15/Feb/2020 01:12:45] "GET /api/WeatherNotice/ HTTP/1.1" 200 1972
[15/Feb/2020 01:12:45] "GET /api/newsinfo/ HTTP/1.1" 200 6721
[15/Feb/2020 01:12:45] "GET /api/sickinfo/ HTTP/1.1" 200 63
[15/Feb/2020 01:12:54] "POST /api/buginfo/ HTTP/1.1" 200 2321
[15/Feb/2020 01:12:54] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:13:04] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:13:14] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:13:15] "GET /api/dustinfo/ HTTP/1.1" 200 212
[15/Feb/2020 01:13:15] "GET /api/WeatherNotice/ HTTP/1.1" 200 1972
[15/Feb/2020 01:13:15] "GET /api/newsinfo/ HTTP/1.1" 200 6721
[15/Feb/2020 01:13:15] "GET /api/sickinfo/ HTTP/1.1" 200 63
[15/Feb/2020 01:13:24] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:13:34] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:13:44] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:13:54] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:14:04] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:14:14] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:14:25] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:14:34] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:14:44] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:14:54] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:15:04] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:15:14] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:15:25] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:15:34] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:15:44] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:15:54] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:16:03] "GET /api/newsinfoList/ HTTP/1.1" 200 16
[15/Feb/2020 01:16:10] "GET /api/dustinfo/ HTTP/1.1" 200 212
[15/Feb/2020 01:16:10] "GET /api/WeatherNotice/ HTTP/1.1" 200 1972
[15/Feb/2020 01:16:10] "GET /api/newsinfo/ HTTP/1.1" 200 6721
[15/Feb/2020 01:16:10] "GET /api/sickinfo/ HTTP/1.1" 200 63
[15/Feb/2020 01:16:24] "GET /api/dustinfo/ HTTP/1.1" 200 212
[15/Feb/2020 01:16:24] "GET /api/WeatherNotice/ HTTP/1.1" 200 1972
[15/Feb/2020 01:16:24] "GET /api/newsinfo/ HTTP/1.1" 200 6721
[15/Feb/2020 01:16:24] "GET /api/sickinfo/ HTTP/1.1" 200 63
[15/Feb/2020 01:16:51] "GET /api/dustinfo/ HTTP/1.1" 200 212
[15/Feb/2020 01:16:51] "GET /api/WeatherNotice/ HTTP/1.1" 200 1972
[15/Feb/2020 01:16:51] "GET /api/newsinfo/ HTTP/1.1" 200 6721
[15/Feb/2020 01:16:51] "GET /api/sickinfo/ HTTP/1.1" 200 63
[15/Feb/2020 01:17:26] "GET /api/WeatherNotice/ HTTP/1.1" 200 1972
[15/Feb/2020 01:17:26] "GET /api/newsinfo/ HTTP/1.1" 200 6721
[15/Feb/2020 01:17:26] "GET /api/dustinfo/ HTTP/1.1" 200 212
[15/Feb/2020 01:17:27] "GET /api/sickinfo/ HTTP/1.1" 200 63
[15/Feb/2020 02:35:31] "GET /api/dustinfo/ HTTP/1.1" 200 212
[15/Feb/2020 02:35:31] "GET /api/newsinfo/ HTTP/1.1" 200 6721
[15/Feb/2020 02:35:31] "GET /api/WeatherNotice/ HTTP/1.1" 200 1972
[15/Feb/2020 02:35:32] "GET /api/sickinfo/ HTTP/1.1" 200 63
[15/Feb/2020 02:36:04] "POST /api/buginfo/ HTTP/1.1" 200 2322
[15/Feb/2020 10:12:20] "GET /api/dustinfo/ HTTP/1.1" 200 212
[15/Feb/2020 10:12:20] "GET /api/newsinfo/ HTTP/1.1" 200 6721
[15/Feb/2020 10:12:20] "GET /api/WeatherNotice/ HTTP/1.1" 200 1972
[15/Feb/2020 10:12:20] "GET /api/sickinfo/ HTTP/1.1" 200 63
[15/Feb/2020 10:13:01] "GET /api/dustinfo/ HTTP/1.1" 200 212
[15/Feb/2020 10:13:01] "GET /api/newsinfo/ HTTP/1.1" 200 6721
[15/Feb/2020 10:13:01] "GET /api/WeatherNotice/ HTTP/1.1" 200 1972
[15/Feb/2020 10:13:02] "GET /api/sickinfo/ HTTP/1.1" 200 63
[15/Feb/2020 10:13:04] "GET /api/WeatherNotice/ HTTP/1.1" 200 1972
[15/Feb/2020 10:13:04] "GET /api/dustinfo/ HTTP/1.1" 200 212
[15/Feb/2020 10:13:04] "GET /api/newsinfo/ HTTP/1.1" 200 6721
[15/Feb/2020 10:13:04] "GET /api/sickinfo/ HTTP/1.1" 200 63
[15/Feb/2020 10:55:44] "GET /api/dustinfo/ HTTP/1.1" 200 212
[15/Feb/2020 10:55:44] "GET /api/newsinfo/ HTTP/1.1" 200 6721
[15/Feb/2020 10:55:44] "GET /api/WeatherNotice/ HTTP/1.1" 200 1972
[15/Feb/2020 10:55:45] "GET /api/sickinfo/ HTTP/1.1" 200 63
----------------------------------------
Exception happened during processing of request from ('124.56.46.29', 54631)
----------------------------------------
Exception happened during processing of request from ('124.56.46.29', 54628)
----------------------------------------
Exception happened during processing of request from ('124.56.46.29', 54630)
----------------------------------------
Exception happened during processing of request from ('124.56.46.29', 54629)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[15/Feb/2020 11:14:44] "GET /api/dustinfo/ HTTP/1.1" 200 212
[15/Feb/2020 11:14:44] "GET /api/newsinfo/ HTTP/1.1" 200 6721
[15/Feb/2020 11:14:44] "GET /api/WeatherNotice/ HTTP/1.1" 200 1972
[15/Feb/2020 11:14:45] "GET /api/sickinfo/ HTTP/1.1" 200 63
[15/Feb/2020 11:15:41] "GET /api/dustinfo/ HTTP/1.1" 200 212
[15/Feb/2020 11:15:41] "GET /api/newsinfo/ HTTP/1.1" 200 6721
[15/Feb/2020 11:15:41] "GET /api/WeatherNotice/ HTTP/1.1" 200 1972
[15/Feb/2020 11:15:42] "GET /api/sickinfo/ HTTP/1.1" 200 63
[15/Feb/2020 11:15:47] "GET /api/dustinfo/ HTTP/1.1" 200 212
[15/Feb/2020 11:15:47] "GET /api/WeatherNotice/ HTTP/1.1" 200 1972
[15/Feb/2020 11:15:47] "GET /api/newsinfo/ HTTP/1.1" 200 6721
[15/Feb/2020 11:15:47] "GET /api/sickinfo/ HTTP/1.1" 200 63
[15/Feb/2020 11:16:08] "GET /api/dustinfo/ HTTP/1.1" 200 212
[15/Feb/2020 11:16:15] "GET /api/newsinfo/ HTTP/1.1" 200 6721
[15/Feb/2020 11:16:18] "GET /api/sickinfo/ HTTP/1.1" 200 63
Internal Server Error: /api/buginfo/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/ubuntu/.local/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/ubuntu/projectback/information/views.py", line 325, in BugList
    crop = search.values('cropname')[0]["cropname"]
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/db/models/query.py", line 314, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
[15/Feb/2020 11:16:23] "POST /api/buginfo/ HTTP/1.1" 500 16356
[15/Feb/2020 11:16:36] "GET /api/WeatherNotice/ HTTP/1.1" 200 1972
[15/Feb/2020 11:38:24] "GET /api/dustinfo/ HTTP/1.1" 200 212
[15/Feb/2020 11:38:24] "GET /api/newsinfo/ HTTP/1.1" 200 6721
[15/Feb/2020 11:38:24] "GET /api/WeatherNotice/ HTTP/1.1" 200 1972
[15/Feb/2020 11:38:24] "GET /api/sickinfo/ HTTP/1.1" 200 63
----------------------------------------
Exception happened during processing of request from ('202.152.24.234', 46787)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('223.38.45.200', 50552)
----------------------------------------
Exception happened during processing of request from ('223.38.45.200', 50554)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('223.38.45.200', 50558)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('223.38.45.200', 50556)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[15/Feb/2020 11:51:31] "GET /api/dustinfo/ HTTP/1.1" 200 212
[15/Feb/2020 11:51:31] "GET /api/newsinfo/ HTTP/1.1" 200 6721
[15/Feb/2020 11:51:31] "GET /api/WeatherNotice/ HTTP/1.1" 200 1972
[15/Feb/2020 11:51:32] "GET /api/sickinfo/ HTTP/1.1" 200 63
[15/Feb/2020 11:53:11] "GET /api/newsinfo/ HTTP/1.1" 200 6721
[15/Feb/2020 11:53:11] "GET /api/dustinfo/ HTTP/1.1" 200 212
[15/Feb/2020 11:53:11] "GET /api/WeatherNotice/ HTTP/1.1" 200 1972
[15/Feb/2020 11:53:12] "GET /api/sickinfo/ HTTP/1.1" 200 63
[15/Feb/2020 11:53:13] "GET /api/weatherinfo/?Lat=37.5633&Lon=126.993 HTTP/1.1" 200 137
[15/Feb/2020 11:55:48] "GET /api/newsinfo/ HTTP/1.1" 200 6721
[15/Feb/2020 11:55:48] "GET /api/WeatherNotice/ HTTP/1.1" 200 1972
[15/Feb/2020 11:55:48] "GET /api/dustinfo/ HTTP/1.1" 200 212
[15/Feb/2020 11:55:49] "GET /api/sickinfo/ HTTP/1.1" 200 63
